services:
  corporate-hub-backend:
    container_name: corporate-hub-backend
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./ssl:/app/ssl
      - ./key.json:/app/key.json
    restart: unless-stopped